In [1]:
import pandas as pd, re

pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_columns', None)

df = pd.read_csv("../data/dane.csv", dtype=str, keep_default_na=False, na_values=[""])

df.head()

  Autonumer    ID pilny                  etap nr zam klienta nr ew zam nr poz zam           data zam plan         termin zam        termin prod kontrahent         model z34 z345 z35 z355 z36 z365 z37 z375 z38 z385 z39 z395 z40 z405 z41 z415 z42 z425 z43 z435 z44 z445 z45 z46 z47 z48 z49 z50 szwalnia szyjąca           przyjete zam surow         oczekujące            rozkrój ploter         ścienianie     przygotowawcza mag kroji kroje niekompletne        na szwalnii chol bez ozdób              MAG 2              MAG 3 Overlock szycie ręczne przedmontażowy przygotowane komplety wklejone zakładki             montaż   zdane na magazyn zlecone do wyprodukowania zrealizowana produkcja zewnętrzna wstrzymane odrzucone wyd oblek obcasy wyd oblek podsuwki wyd oblek podpodeszwy kto obleka obcas kto obleka podsuwka kto obleka podpodeszwa zrealizowno oblek obcas zrealizowno oblek podsuwka zrealizowno oblek podpodeszwa uwagi prod uwagi inne uwagi całe zamówienie              pudełko nr 2 zam klienta drukowano plan wydruk etykiet              pole1 pole2 pole3 pole4   pole5 pole6 pole7 pole8 pole9 pole10 pole11 pole12 pole13 pole14 pole15
0      6760  6760   NaN  11. zdane na magazyn       1/sklepy         2         16  03/21/17 00:00:00   71  03/31/17 00:00:00  04/07/17 00:00:00   111 - 52  4483-69-1153   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:26       NaN  03/24/17 16:19:39  03/28/17 12:54:33    NaN  04/01/17 11:02:53  04/03/17 06:32:41       NaN                NaN  04/03/17 12:22:23            NaN  04/26/17 14:27:08  05/18/17 12:29:49      NaN           NaN            NaN     05/18/17 12:33:24               NaN  05/19/17 11:33:01  05/19/17 11:34:24                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:46:05   NaN   NaN   NaN  SKLEPY     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
1      6767  6767   NaN  11. zdane na magazyn       1/sklepy         2         23  03/21/17 00:00:00   70  03/31/17 00:00:00  04/07/17 00:00:00   111 - 36  4483-69-1153   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:26       NaN  03/24/17 16:19:39  03/28/17 12:33:25    NaN  04/01/17 10:56:05  04/03/17 06:32:48       NaN                NaN  04/06/17 08:59:47            NaN  04/06/17 09:00:09  04/06/17 09:03:18      NaN           NaN            NaN     04/13/17 07:27:04               NaN  04/26/17 07:21:32  04/26/17 09:48:54                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:46:12   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
2      6771  6771   NaN  11. zdane na magazyn       1/sklepy         2         27  03/21/17 00:00:00   77  03/31/17 00:00:00  04/11/17 00:00:00   111 - 54  4483-69-1208   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:58       NaN  03/24/17 16:19:39  03/28/17 12:27:52    NaN  04/01/17 11:03:42  04/03/17 06:31:46       NaN                NaN  04/03/17 12:22:07            NaN  04/06/17 06:05:45  04/06/17 06:07:49      NaN           NaN            NaN     04/11/17 08:55:50               NaN  04/13/17 11:01:11  04/19/17 07:42:07                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:44:20   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
3      6772  6772   NaN  11. zdane na magazyn       1/sklepy         2         28  03/21/17 00:00:00   76  03/31/17 00:00:00  04/11/17 00:00:00  111 - B2C  4483-69-1208   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:58       NaN  03/24/17 16:19:39  03/28/17 12:28:30    NaN  03/30/17 16:04:29  03/31/17 06:23:39       NaN                NaN  03/31/17 09:52:54            NaN  04/06/17 06:05:38  04/06/17 06:07:58      NaN           NaN            NaN     04/11/17 08:43:23               NaN  04/19/17 07:00:11  04/19/17 11:02:19                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  03/31/17 08:19:45   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
4      6777  6777   NaN  11. zdane na magazyn       1/sklepy         2         33  03/21/17 00:00:00   77  03/31/17 00:00:00  04/11/17 00:00:00   111 - 12  4483-69-1208   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:58       NaN  03/24/17 16:19:39  03/28/17 12:27:52    NaN  04/01/17 11:03:42  04/03/17 06:31:46       NaN                NaN  04/03/17 12:22:07            NaN  04/06/17 06:05:45  04/06/17 06:07:49      NaN           NaN            NaN     04/11/17 08:55:50               NaN  04/13/17 11:01:11  04/19/17 07:42:07                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:44:20   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN

In [2]:
df.columns

Index(['Autonumer', 'ID', 'pilny', 'etap', 'nr zam klienta', 'nr ew zam',
       'nr poz zam', 'data zam', 'plan', 'termin zam', 'termin prod',
       'kontrahent', 'model', 'z34', 'z345', 'z35', 'z355', 'z36', 'z365',
       'z37', 'z375', 'z38', 'z385', 'z39', 'z395', 'z40', 'z405', 'z41',
       'z415', 'z42', 'z425', 'z43', 'z435', 'z44', 'z445', 'z45', 'z46',
       'z47', 'z48', 'z49', 'z50', 'szwalnia szyjąca', 'przyjete', 'zam surow',
       'oczekujące', 'rozkrój', 'ploter', 'ścienianie', 'przygotowawcza',
       'mag kroji', 'kroje niekompletne', 'na szwalnii', 'chol bez ozdób',
       'MAG 2', 'MAG 3', 'Overlock', 'szycie ręczne', 'przedmontażowy',
       'przygotowane komplety', 'wklejone zakładki', 'montaż',
       'zdane na magazyn', 'zlecone do wyprodukowania',
       'zrealizowana produkcja zewnętrzna', 'wstrzymane', 'odrzucone',
       'wyd oblek obcasy', 'wyd oblek podsuwki', 'wyd oblek podpodeszwy',
       'kto obleka obcas', 'kto obleka podsuwka', 'kto obleka podpodeszwa',
       'zrealizowno oblek obcas', 'zrealizowno oblek podsuwka',
       'zrealizowno oblek podpodeszwa', 'uwagi prod', 'uwagi inne',
       'uwagi całe zamówienie', 'pudełko', 'nr 2 zam klienta',
       'drukowano plan', 'wydruk etykiet', 'pole1', 'pole2', 'pole3', 'pole4',
       'pole5', 'pole6', 'pole7', 'pole8', 'pole9', 'pole10', 'pole11',
       'pole12', 'pole13', 'pole14', 'pole15'],
      dtype='str')

In [3]:
df.shape

(30885, 97)

In [4]:
display(df['nr zam klienta'])

0        1/sklepy
1        1/sklepy
2        1/sklepy
3        1/sklepy
4        1/sklepy
           ...
30880         151
30881         191
30882         170
30883         155
30884         191
Name: nr zam klienta, Length: 30885, dtype: str

In [5]:
DATE_RE = re.compile(r"^\s*\d{1,2}[/-]\d{1,2}[/-]\d{2,4}([ T]\d{1,2}:\d{2}(:\d{2})?)?\s*$")

date_cols, empty_cols, mixed = [], [], {}
for c in df.columns:
    s = df[c].dropna()
    if s.empty:
        empty_cols.append(c)          # brak danych -> nie da się orzec
        continue
    hit = s.str.match(DATE_RE).mean()
    if hit == 1.0:
        date_cols.append(c)
    elif hit > 0:
        mixed[c] = hit                # do ręcznego obejrzenia/

In [6]:
display(date_cols)

['data zam',
 'termin zam',
 'termin prod',
 'przyjete',
 'oczekujące',
 'rozkrój',
 'ploter',
 'ścienianie',
 'przygotowawcza',
 'na szwalnii',
 'MAG 2',
 'MAG 3',
 'Overlock',
 'przedmontażowy',
 'przygotowane komplety',
 'montaż',
 'zdane na magazyn',
 'zlecone do wyprodukowania',
 'zrealizowana produkcja zewnętrzna',
 'wstrzymane',
 'odrzucone',
 'drukowano plan',
 'wydruk etykiet',
 'pole1',
 'pole2',
 'pole3']

In [7]:
display(empty_cols)

['zam surow',
 'mag kroji',
 'kroje niekompletne',
 'chol bez ozdób',
 'szycie ręczne',
 'wklejone zakładki',
 'wyd oblek obcasy',
 'wyd oblek podsuwki',
 'wyd oblek podpodeszwy',
 'kto obleka obcas',
 'kto obleka podsuwka',
 'kto obleka podpodeszwa',
 'zrealizowno oblek obcas',
 'zrealizowno oblek podsuwka',
 'zrealizowno oblek podpodeszwa',
 'pole7',
 'pole8',
 'pole9',
 'pole10',
 'pole11',
 'pole12',
 'pole13',
 'pole14',
 'pole15']

In [8]:
print(len(empty_cols))

24

In [9]:
df['Autonumer'].duplicated().any()

np.False_

In [10]:
df['Autonumer'].nunique()

30885

In [11]:
df.duplicated().any()

np.False_

In [12]:
display(df['ID'].duplicated().any())
display(df['ID'].duplicated().sum())

np.True_

np.int64(234)

In [13]:
df[df['ID'].duplicated(keep=False)].sort_values('ID').head(4)

      Autonumer     ID pilny                  etap nr zam klienta nr ew zam nr poz zam           data zam  plan         termin zam        termin prod kontrahent          model z34 z345 z35 z355 z36 z365 z37 z375 z38 z385 z39 z395 z40 z405 z41 z415 z42 z425 z43 z435 z44 z445 z45 z46 z47 z48 z49 z50 szwalnia szyjąca           przyjete zam surow         oczekujące            rozkrój             ploter         ścienianie     przygotowawcza mag kroji kroje niekompletne        na szwalnii chol bez ozdób              MAG 2              MAG 3 Overlock szycie ręczne przedmontażowy przygotowane komplety wklejone zakładki             montaż   zdane na magazyn zlecone do wyprodukowania zrealizowana produkcja zewnętrzna         wstrzymane odrzucone wyd oblek obcasy wyd oblek podsuwki wyd oblek podpodeszwy kto obleka obcas kto obleka podsuwka kto obleka podpodeszwa zrealizowno oblek obcas zrealizowno oblek podsuwka zrealizowno oblek podpodeszwa uwagi prod        uwagi inne uwagi całe zamówienie pudełko nr 2 zam klienta drukowano plan wydruk etykiet              pole1 pole2 pole3 pole4             pole5 pole6 pole7 pole8 pole9 pole10 pole11 pole12 pole13 pole14 pole15
5911      18361  18361   NaN  11. zdane na magazyn            201         0          0  05/31/17 00:00:00  2692  08/07/17 00:00:00  10/19/17 00:00:00   111 - 47  9351-69-981-M   0    0   0    0   1    0   2    0   2    0   2    0   0    0   1    0   0    0   0    0   0    0   0   0   0   0   0   0                8  06/02/17 14:06:36       NaN  09/22/17 12:02:44  09/28/17 10:13:25                NaN  10/11/17 15:02:17  10/12/17 07:16:11       NaN                NaN  10/30/17 15:09:27            NaN  11/27/17 13:10:37  11/27/17 13:12:11      NaN           NaN            NaN     11/28/17 05:58:32               NaN  12/06/17 15:16:08  12/13/17 13:03:36                       NaN                               NaN  06/02/17 00:00:00       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN  SUWALKI-PLAZA-47                   NaN     NaN              NaN            NaN            NaN  10/12/17 14:43:51   NaN   NaN   NaN            SKLEPY     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
18525     40963  18361   NaN             2 gatunek            201         0          0  05/31/17 00:00:00  2692  08/07/17 00:00:00  10/19/17 00:00:00   111 - 47  9351-69-981-M   0    0   0    0   0    0   0    0   0    0   0    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                8  06/02/17 14:06:36       NaN  09/22/17 12:02:44  09/28/17 10:13:25                NaN  10/11/17 15:02:17  10/12/17 07:16:11       NaN                NaN  10/30/17 15:09:27            NaN  11/27/17 13:10:37  11/27/17 13:12:11      NaN           NaN            NaN     11/28/17 05:58:32               NaN  12/06/17 15:16:08                NaN                       NaN                               NaN  06/02/17 00:00:00       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN  SUWALKI-PLAZA-47                   NaN     NaN              NaN            NaN            NaN  10/12/17 14:43:51   NaN   NaN   NaN            SKLEPY     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
18671     41109  29968   NaN             2 gatunek          20062         0          0  09/22/17 00:00:00  3288  11/21/17 00:00:00  02/07/18 00:00:00  200-72000    1494-69-433   0    0   0    0   0    0   0    0   0    0   0    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0               12  09/26/17 13:07:40       NaN  10/28/17 07:55:27                NaN  11/15/17 09:51:39  11/23/17 06:54:35  11/24/17 08:09:35       NaN                NaN  11/29/17 06:33:51            NaN  12/05/17 13:30:27  12/05/17 13:31:30      NaN           NaN            NaN     12/06/17 08:17:10               NaN  12/07/17 14:03:26                NaN                       NaN                               NaN  10/18/17 14:34:59       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN   wysyłka: Grójec                   NaN     NaN        20062//BA            NaN            NaN  11/24/17 14:55:05   NaN   NaN   NaN  SKLEPY+SORBOS+DH     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
8077      29968  29968   NaN  11. zdane na magazyn          20062         0          0  09/22/17 00:00:00  3288  11/21/17 00:00:00  02/07/18 00:00:00  200-72000    1494-69-433   0    0   0    0   1    0   1    0   2    0   2    0   0    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0               12  09/26/17 13:07:40       NaN  10/28/17 07:55:27                NaN  11/15/17 09:51:39  11/23/17 06:54:35  11/24/17 08:09:35       NaN                NaN  11/29/17 06:33:51            NaN  12/05/17 13:30:27  12/05/17 13:31:30      NaN           NaN            NaN     12/06/17 08:17:10               NaN  12/07/17 14:03:26  12/15/17 12:57:33                       NaN                               NaN  10/18/17 14:34:59       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN   wysyłka: Grójec                   NaN     NaN        20062//BA            NaN            NaN  11/24/17 14:55:05   NaN   NaN   NaN  SKLEPY+SORBOS+DH     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN

In [14]:
df[df['ID'].duplicated(keep=False)].groupby('ID').nunique(dropna=True).gt(1).sum().sort_values(ascending=False).loc[lambda s: s > 0]

Autonumer    233
etap         233
z36          212
z40          210
z38          189
z39          178
z37          163
z375          13
z395          13
z385          13
z365          12
z35            7
z41            5
dtype: int64

In [15]:
size_cols = [
    "z34", "z345", "z35", "z355", "z36", "z365",
    "z37", "z375", "z38", "z385", "z39", "z395",
    "z40", "z405", "z41", "z415", "z42", "z425",
    "z43", "z435", "z44", "z445", "z45", "z46",
    "z47", "z48", "z49", "z50"
]

cols_to_skip = set(size_cols + ["etap"] + ['ID'])

duplikaty_id = df[df.duplicated("ID", keep=False)].copy()

def rozniace_sie_kolumny(grupa):
    roznice = []

    for col in df.columns:
        if col in cols_to_skip:
            continue

        wartosci = grupa[col].astype("string").fillna("").unique()

        if len(wartosci) > 1:
            roznice.append(col)

    return roznice

raport_roznic = (
    duplikaty_id
    .groupby("ID", group_keys=False)
    .apply(rozniace_sie_kolumny)
    .rename("roznice_poza_etapem_i_rozmiarowka")
)

raport_roznic.head()

ID
18361    [Autonumer, zdane na magazyn]
29968    [Autonumer, zdane na magazyn]
30547    [Autonumer, zdane na magazyn]
30553    [Autonumer, zdane na magazyn]
30559    [Autonumer, zdane na magazyn]
Name: roznice_poza_etapem_i_rozmiarowka, dtype: object

In [16]:
raport_roznic.value_counts()

roznice_poza_etapem_i_rozmiarowka
[Autonumer, zdane na magazyn]    233
Name: count, dtype: int64

In [17]:
df['etap'].nunique()

26

In [18]:
df['etap'].value_counts()

etap
11. zdane na magazyn      21695
odrzucone                  3355
wstrzymane                 1384
8. przyg komplety          1130
2. oczekujące               673
7. MAG 3                    520
Szwalnia 6                  420
0c                          230
2 gatunek                   222
1b. zam krótki termin       221
4b. przygotowawcza          194
4. ścienianie               174
1a. zam długi termin        152
3. rozkrój                  106
3p. ploter                  102
6. MAG 2                     64
5k. komplety szwalnia        56
10. montaż                   51
Szwalnia 1                   38
B2. wydane 2 komplety        31
Szwalnia 5                   25
Szwalnia 10                  20
uszkodzone anulowane         12
7o. Overlock                  6
7p. Mag przedmontażowy        2
10b. montaż 2                 2
Name: count, dtype: int64

In [19]:
df['kontrahent'].nunique()

279

In [20]:
df['kontrahent'].value_counts()

kontrahent
200-100        3309
200-2165       1612
200-0012       1250
EVA MINGE      1003
114 - B2C       901
               ...
LA MANIA          1
OTICO             1
088               1
200-2             1
200-40928/2       1
Name: count, Length: 279, dtype: int64

In [21]:
df['model'].nunique()

1816

In [22]:
df['model'].value_counts()

model
7769-69-124-F      167
8137-69-077-F      145
9301-69-1062-M     129
7744-69-113-M      127
7787-69-010        117
                  ...
9373-69-1596-WF      1
6339-69-1630         1
6371-69-1017-L       1
6431-69-1056-L       1
1528-69-015          1
Name: count, Length: 1816, dtype: int64

In [23]:
df['szwalnia szyjąca'].nunique()

11

In [24]:
df['szwalnia szyjąca'].value_counts()

szwalnia szyjąca
6     14087
0      9169
1      3114
10     1174
5      1085
12      997
8       915
7       272
11       51
13       14
9         7
Name: count, dtype: int64

In [25]:
df = df.copy()
df = df.drop(columns=empty_cols)
df.shape

(30885, 73)

In [26]:
for c in date_cols:
    df[c] = pd.to_datetime(df[c], errors='coerce', format ='%m/%d/%y %H:%M:%S')

In [27]:
df[date_cols].dtypes
df[date_cols].head()

    data zam termin zam termin prod            przyjete          oczekujące             rozkrój ploter          ścienianie      przygotowawcza         na szwalnii               MAG 2               MAG 3 Overlock przedmontażowy przygotowane komplety              montaż    zdane na magazyn zlecone do wyprodukowania zrealizowana produkcja zewnętrzna wstrzymane odrzucone drukowano plan wydruk etykiet               pole1 pole2 pole3
0 2017-03-21 2017-03-31  2017-04-07 2017-03-21 08:54:26 2017-03-24 16:19:39 2017-03-28 12:54:33    NaT 2017-04-01 11:02:53 2017-04-03 06:32:41 2017-04-03 12:22:23 2017-04-26 14:27:08 2017-05-18 12:29:49      NaT            NaT   2017-05-18 12:33:24 2017-05-19 11:33:01 2017-05-19 11:34:24                       NaT                               NaT        NaT       NaT            NaT            NaT 2017-04-03 07:46:05   NaT   NaT
1 2017-03-21 2017-03-31  2017-04-07 2017-03-21 08:54:26 2017-03-24 16:19:39 2017-03-28 12:33:25    NaT 2017-04-01 10:56:05 2017-04-03 06:32:48 2017-04-06 08:59:47 2017-04-06 09:00:09 2017-04-06 09:03:18      NaT            NaT   2017-04-13 07:27:04 2017-04-26 07:21:32 2017-04-26 09:48:54                       NaT                               NaT        NaT       NaT            NaT            NaT 2017-04-03 07:46:12   NaT   NaT
2 2017-03-21 2017-03-31  2017-04-11 2017-03-21 08:54:58 2017-03-24 16:19:39 2017-03-28 12:27:52    NaT 2017-04-01 11:03:42 2017-04-03 06:31:46 2017-04-03 12:22:07 2017-04-06 06:05:45 2017-04-06 06:07:49      NaT            NaT   2017-04-11 08:55:50 2017-04-13 11:01:11 2017-04-19 07:42:07                       NaT                               NaT        NaT       NaT            NaT            NaT 2017-04-03 07:44:20   NaT   NaT
3 2017-03-21 2017-03-31  2017-04-11 2017-03-21 08:54:58 2017-03-24 16:19:39 2017-03-28 12:28:30    NaT 2017-03-30 16:04:29 2017-03-31 06:23:39 2017-03-31 09:52:54 2017-04-06 06:05:38 2017-04-06 06:07:58      NaT            NaT   2017-04-11 08:43:23 2017-04-19 07:00:11 2017-04-19 11:02:19                       NaT                               NaT        NaT       NaT            NaT            NaT 2017-03-31 08:19:45   NaT   NaT
4 2017-03-21 2017-03-31  2017-04-11 2017-03-21 08:54:58 2017-03-24 16:19:39 2017-03-28 12:27:52    NaT 2017-04-01 11:03:42 2017-04-03 06:31:46 2017-04-03 12:22:07 2017-04-06 06:05:45 2017-04-06 06:07:49      NaT            NaT   2017-04-11 08:55:50 2017-04-13 11:01:11 2017-04-19 07:42:07                       NaT                               NaT        NaT       NaT            NaT            NaT 2017-04-03 07:44:20   NaT   NaT

In [28]:
date_cols = [c for c in date_cols if c != 'pole1']
if 'przygotowane komplety' not in date_cols:
    date_cols.append('przygotowane komplety')

In [29]:
for poprzedni, nastepny in zip(date_cols, date_cols[1:]):
    blad = (
        df[poprzedni].notna()
        & df[nastepny].notna()
        & (df[nastepny] < df[poprzedni])
    )

    if blad.any():
        print(f'Błąd: {nastepny} jest przed {poprzedni}')
        display(df.loc[blad, ['ID', poprzedni, nastepny]])

Błąd: termin zam jest przed data zam

          ID   data zam termin zam
5689   18049 2017-05-30 2017-05-15
7799   24681 2017-09-21 2017-02-15
7800   24682 2017-09-21 2017-02-15
7801   24683 2017-09-21 2017-02-15
7802   24684 2017-09-21 2017-02-15
...      ...        ...        ...
29510  52180 2018-05-08 2018-05-06
29511  52181 2018-05-08 2018-05-06
29512  52182 2018-05-08 2018-05-06
29513  52183 2018-05-08 2018-05-06
29545  52215 2018-05-08 2018-05-06

[335 rows x 3 columns]

Błąd: termin prod jest przed termin zam

          ID termin zam termin prod
31      7579 2017-08-24  2017-08-15
111     7682 2017-08-24  2017-08-15
276     8026 2017-08-24  2017-08-15
294     8059 2017-08-24  2017-07-17
358     8195 2017-08-24  2017-08-20
...      ...        ...         ...
30393  53303 2018-08-01  2018-07-15
30430  51435 2018-08-15  2018-05-30
30437  53347 2018-08-01  2018-07-15
30438  53348 2018-08-01  2018-07-15
30882  48245 2018-08-15  2018-05-04

[2479 rows x 3 columns]

Błąd: przyjete jest przed termin prod

          ID termin prod            przyjete
0       6760  2017-04-07 2017-03-21 08:54:26
1       6767  2017-04-07 2017-03-21 08:54:26
2       6771  2017-04-11 2017-03-21 08:54:58
3       6772  2017-04-11 2017-03-21 08:54:58
4       6777  2017-04-11 2017-03-21 08:54:58
...      ...         ...                 ...
30880  49020  2018-06-22 2018-03-07 09:12:52
30881  52318  2018-05-30 2018-05-08 12:06:11
30882  48245  2018-05-04 2018-03-06 08:56:26
30883  51097  2018-04-30 2018-04-16 10:17:33
30884  52196  2018-05-22 2018-05-08 12:06:11

[25123 rows x 3 columns]

Błąd: na szwalnii jest przed przygotowawcza

          ID      przygotowawcza         na szwalnii
8429   30324 2018-01-02 06:13:12 2017-12-29 06:46:46
8720   30627 2018-01-02 06:13:12 2017-12-29 06:46:46
8833   30744 2018-01-02 06:13:12 2017-12-29 06:46:46
15350  37720 2018-01-02 06:13:12 2017-12-29 06:46:46
17224  39645 2018-01-02 06:13:12 2017-12-29 06:46:46
18881  41319 2018-01-30 15:54:50 2018-01-30 12:43:46
18882  41320 2018-01-30 15:54:50 2018-01-30 12:43:46
18883  41321 2018-01-30 15:54:50 2018-01-30 12:43:46
18884  41322 2018-01-30 15:54:50 2018-01-30 12:43:46
18885  41323 2018-01-30 15:54:50 2018-01-30 12:43:46
18886  41324 2018-01-30 15:54:50 2018-01-30 12:43:46
18887  41325 2018-01-30 15:54:50 2018-01-30 12:43:46
18888  41326 2018-01-30 15:54:50 2018-01-30 12:43:46
18889  41327 2018-01-30 15:54:50 2018-01-30 12:43:46
18890  41328 2018-01-30 15:54:50 2018-01-30 12:43:46

Błąd: MAG 2 jest przed na szwalnii

          ID         na szwalnii               MAG 2
2279   12025 2017-06-06 12:50:25 2017-05-31 11:57:51
2724   12738 2017-04-28 12:27:35 2017-04-28 06:49:45
2731   12773 2017-06-06 12:49:28 2017-05-31 11:57:34
2810   12982 2017-04-28 12:27:35 2017-04-28 06:49:45
4090   15903 2017-06-06 12:49:28 2017-05-31 11:57:34
6644   19595 2017-09-01 06:20:55 2017-08-31 06:57:02
6648   19599 2017-09-01 06:20:55 2017-08-31 06:57:02
6651   19602 2017-09-01 06:20:55 2017-08-31 06:57:02
6652   19603 2017-09-01 06:20:55 2017-08-31 06:57:02
6653   19604 2017-09-01 06:20:55 2017-08-31 06:57:02
7824   24707 2018-02-01 07:22:06 2018-01-31 08:06:13
8650   30555 2018-02-01 07:22:06 2018-01-31 08:06:13
9809   31769 2018-02-01 07:22:06 2018-01-31 08:06:13
10068  32043 2018-02-01 07:22:06 2018-01-31 08:06:13
10973  32991 2018-02-01 07:22:06 2018-01-31 08:06:13
14533  36803 2018-02-01 06:16:30 2018-01-30 12:53:34
16049  38419 2017-12-19 15:34:29 2017-12-01 08:28:49
16050  38420 2017-12-19 10:45:40 2017-12-01 08:28:40
16051  38421 2017-12-19 15:34:29 2017-12-01 08:28:49
16052  38422 2017-12-19 15:34:29 2017-12-01 08:28:49
16054  38424 2017-12-19 15:34:29 2017-12-01 08:28:49
16055  38425 2017-12-19 15:34:29 2017-12-01 08:28:49
16057  38427 2017-12-19 10:45:40 2017-12-01 08:28:40
16058  38428 2017-12-19 10:45:40 2017-12-01 08:28:40
16059  38429 2017-12-19 10:45:40 2017-12-01 08:28:40
16060  38430 2017-12-19 10:45:40 2017-12-01 08:28:40
16296  38672 2017-12-19 15:35:14 2017-12-01 08:28:29
16297  38673 2017-12-19 15:35:14 2017-12-01 08:28:29
16299  38675 2017-12-19 15:35:14 2017-12-01 08:28:29
16300  38676 2017-12-19 15:35:14 2017-12-01 08:28:29
16302  38678 2017-12-19 15:35:14 2017-12-01 08:28:29
16303  38679 2017-12-19 15:35:14 2017-12-01 08:28:29
16304  38680 2017-12-19 15:35:14 2017-12-01 08:28:29
21087  43527 2018-04-04 06:08:26 2018-03-29 06:13:40
21300  43746 2018-04-04 06:08:26 2018-03-29 06:13:40
21576  44032 2018-04-04 06:05:46 2018-03-29 06:14:40
21990  44461 2018-04-04 06:08:26 2018-03-29 06:13:40
22118  44592 2018-04-04 06:08:26 2018-03-29 06:13:40
22462  44945 2018-04-04 06:05:46 2018-03-29 06:14:40
22573  45060 2018-04-04 06:08:26 2018-03-29 06:13:40
22703  45193 2018-04-04 06:08:26 2018-03-29 06:13:40
23014  45510 2018-04-04 06:05:46 2018-03-29 06:14:40
23343  45855 2018-04-04 06:05:46 2018-03-29 06:14:40
23535  46063 2018-04-04 06:05:46 2018-03-29 06:14:40
23914  46475 2018-04-04 06:05:46 2018-03-29 06:14:40

Błąd: Overlock jest przed MAG 3

          ID               MAG 3            Overlock
7605   20837 2018-02-05 06:09:04 2018-01-31 11:49:15
7606   20838 2018-02-27 10:51:03 2018-02-08 14:28:39
7610   20842 2018-02-27 10:51:03 2018-02-08 14:28:39
7613   20845 2018-02-27 10:51:03 2018-02-08 14:28:39
7638   24519 2018-03-05 11:22:38 2018-02-14 14:21:08
...      ...                 ...                 ...
29655  52325 2018-05-25 07:02:59 2018-05-24 14:50:25
29656  52326 2018-05-25 07:02:59 2018-05-24 14:50:25
29657  52327 2018-05-28 07:37:04 2018-05-22 08:36:59
29658  52328 2018-05-28 07:37:04 2018-05-22 08:36:59
29659  52329 2018-05-28 07:37:04 2018-05-22 08:36:59

[387 rows x 3 columns]

Błąd: zdane na magazyn jest przed montaż

          ID              montaż    zdane na magazyn
6934   19974 2017-10-10 14:12:09 2017-10-10 14:12:06
26457  49127 2018-05-08 12:05:35 2018-05-08 12:05:34
27901  50571 2018-04-26 12:41:37 2018-04-26 12:40:56
28857  51527 2018-05-23 12:05:07 2018-05-23 12:04:47
28874  51544 2018-05-23 12:05:07 2018-05-23 12:04:47
28878  51548 2018-05-23 12:05:07 2018-05-23 12:04:47
28884  51554 2018-05-23 12:05:07 2018-05-23 12:04:47

Błąd: zlecone do wyprodukowania jest przed zdane na magazyn

          ID    zdane na magazyn zlecone do wyprodukowania
60      7597 2017-10-19 10:13:23       2017-08-31 09:58:37
61      7598 2017-11-03 10:27:08       2017-08-31 09:58:37
73      7626 2017-10-02 06:27:09       2017-06-06 09:49:00
74      7627 2017-08-07 10:08:24       2017-05-31 14:25:25
87      7641 2017-09-29 08:01:03       2017-06-08 11:19:35
...      ...                 ...                       ...
29562  52232 2018-05-24 14:35:05       2018-05-09 08:35:14
29563  52233 2018-05-24 14:35:05       2018-05-09 08:35:14
29564  52234 2018-05-24 14:35:05       2018-05-09 08:35:14
29566  52236 2018-05-24 14:35:05       2018-05-09 08:35:14
29567  52237 2018-05-24 14:35:05       2018-05-09 08:35:14

[1825 rows x 3 columns]

Błąd: wstrzymane jest przed zrealizowana produkcja zewnętrzna

          ID zrealizowana produkcja zewnętrzna wstrzymane
60      7597               2017-10-19 10:11:34 2017-04-05
61      7598               2017-11-03 10:26:25 2017-04-05
62      7599               2017-10-05 07:22:44 2017-04-05
63      7600               2017-10-10 10:38:01 2017-04-05
73      7626               2017-09-29 09:43:40 2017-04-05
...      ...                               ...        ...
29562  52232               2018-05-24 14:34:06 2018-05-08
29563  52233               2018-05-24 14:34:06 2018-05-08
29564  52234               2018-05-24 14:34:06 2018-05-08
29566  52236               2018-05-24 14:34:06 2018-05-08
29567  52237               2018-05-24 14:34:06 2018-05-08

[2271 rows x 3 columns]

In [ ]:
df = df.copy()
import numpy as np

df.insert(
    loc=0,
    column='czas produkcji',
    value=df['zdane na magazyn'] - df['rozkrój']
)

loc = df.columns.get_loc('na szwalnii')
df.insert(
    loc=loc,
    column='komplety szwalnia',
    value=df['pole1']
)

df = df.drop(columns='pole1')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [31]:
df.insert(
    df.columns.get_loc('z34'),
    'liczba par',
    df[size_cols].apply(pd.to_numeric, errors='coerce').fillna(0).sum(axis=1).astype(int)
)
df = df.drop(columns=size_cols)

In [32]:
df.head()

    czas produkcji Autonumer    ID pilny                  etap nr zam klienta nr ew zam nr poz zam   data zam plan termin zam termin prod kontrahent         model  liczba par szwalnia szyjąca            przyjete          oczekujące             rozkrój ploter          ścienianie      przygotowawcza   komplety szwalnia         na szwalnii               MAG 2               MAG 3 Overlock przedmontażowy przygotowane komplety              montaż    zdane na magazyn zlecone do wyprodukowania zrealizowana produkcja zewnętrzna wstrzymane odrzucone uwagi prod uwagi inne uwagi całe zamówienie              pudełko nr 2 zam klienta drukowano plan wydruk etykiet pole2 pole3 pole4   pole5 pole6
0 51 days 22:39:51      6760  6760   NaN  11. zdane na magazyn       1/sklepy         2         16 2017-03-21   71 2017-03-31  2017-04-07   111 - 52  4483-69-1153           8                6 2017-03-21 08:54:26 2017-03-24 16:19:39 2017-03-28 12:54:33    NaT 2017-04-01 11:02:53 2017-04-03 06:32:41 2017-04-03 07:46:05 2017-04-03 12:22:23 2017-04-26 14:27:08 2017-05-18 12:29:49      NaT            NaT   2017-05-18 12:33:24 2017-05-19 11:33:01 2017-05-19 11:34:24                       NaT                               NaT        NaT       NaT          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaT            NaT   NaT   NaT   NaN  SKLEPY     2
1 28 days 21:15:29      6767  6767   NaN  11. zdane na magazyn       1/sklepy         2         23 2017-03-21   70 2017-03-31  2017-04-07   111 - 36  4483-69-1153           8                6 2017-03-21 08:54:26 2017-03-24 16:19:39 2017-03-28 12:33:25    NaT 2017-04-01 10:56:05 2017-04-03 06:32:48 2017-04-03 07:46:12 2017-04-06 08:59:47 2017-04-06 09:00:09 2017-04-06 09:03:18      NaT            NaT   2017-04-13 07:27:04 2017-04-26 07:21:32 2017-04-26 09:48:54                       NaT                               NaT        NaT       NaT          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaT            NaT   NaT   NaT   NaN  SKLEPY     1
2 21 days 19:14:15      6771  6771   NaN  11. zdane na magazyn       1/sklepy         2         27 2017-03-21   77 2017-03-31  2017-04-11   111 - 54  4483-69-1208           8                6 2017-03-21 08:54:58 2017-03-24 16:19:39 2017-03-28 12:27:52    NaT 2017-04-01 11:03:42 2017-04-03 06:31:46 2017-04-03 07:44:20 2017-04-03 12:22:07 2017-04-06 06:05:45 2017-04-06 06:07:49      NaT            NaT   2017-04-11 08:55:50 2017-04-13 11:01:11 2017-04-19 07:42:07                       NaT                               NaT        NaT       NaT          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaT            NaT   NaT   NaT   NaN  SKLEPY     1
3 21 days 22:33:49      6772  6772   NaN  11. zdane na magazyn       1/sklepy         2         28 2017-03-21   76 2017-03-31  2017-04-11  111 - B2C  4483-69-1208           8                6 2017-03-21 08:54:58 2017-03-24 16:19:39 2017-03-28 12:28:30    NaT 2017-03-30 16:04:29 2017-03-31 06:23:39 2017-03-31 08:19:45 2017-03-31 09:52:54 2017-04-06 06:05:38 2017-04-06 06:07:58      NaT            NaT   2017-04-11 08:43:23 2017-04-19 07:00:11 2017-04-19 11:02:19                       NaT                               NaT        NaT       NaT          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaT            NaT   NaT   NaT   NaN  SKLEPY     1
4 21 days 19:14:15      6777  6777   NaN  11. zdane na magazyn       1/sklepy         2         33 2017-03-21   77 2017-03-31  2017-04-11   111 - 12  4483-69-1208           8                6 2017-03-21 08:54:58 2017-03-24 16:19:39 2017-03-28 12:27:52    NaT 2017-04-01 11:03:42 2017-04-03 06:31:46 2017-04-03 07:44:20 2017-04-03 12:22:07 2017-04-06 06:05:45 2017-04-06 06:07:49      NaT            NaT   2017-04-11 08:55:50 2017-04-13 11:01:11 2017-04-19 07:42:07                       NaT                               NaT        NaT       NaT          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaT            NaT   NaT   NaT   NaN  SKLEPY     1