In [1]:
import pandas as pd, re

pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_columns', None)

df = pd.read_csv("../data/dane.csv", dtype=str, keep_default_na=False, na_values=[""])

df.head()

  Autonumer    ID pilny                  etap nr zam klienta nr ew zam nr poz zam           data zam plan         termin zam        termin prod kontrahent         model z34 z345 z35 z355 z36 z365 z37 z375 z38 z385 z39 z395 z40 z405 z41 z415 z42 z425 z43 z435 z44 z445 z45 z46 z47 z48 z49 z50 szwalnia szyjąca           przyjete zam surow         oczekujące            rozkrój ploter         ścienianie     przygotowawcza mag kroji kroje niekompletne        na szwalnii chol bez ozdób              MAG 2              MAG 3 Overlock szycie ręczne przedmontażowy przygotowane komplety wklejone zakładki             montaż   zdane na magazyn zlecone do wyprodukowania zrealizowana produkcja zewnętrzna wstrzymane odrzucone wyd oblek obcasy wyd oblek podsuwki wyd oblek podpodeszwy kto obleka obcas kto obleka podsuwka kto obleka podpodeszwa zrealizowno oblek obcas zrealizowno oblek podsuwka zrealizowno oblek podpodeszwa uwagi prod uwagi inne uwagi całe zamówienie              pudełko nr 2 zam klienta drukowano plan wydruk etykiet              pole1 pole2 pole3 pole4   pole5 pole6 pole7 pole8 pole9 pole10 pole11 pole12 pole13 pole14 pole15
0      6760  6760   NaN  11. zdane na magazyn       1/sklepy         2         16  03/21/17 00:00:00   71  03/31/17 00:00:00  04/07/17 00:00:00   111 - 52  4483-69-1153   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:26       NaN  03/24/17 16:19:39  03/28/17 12:54:33    NaN  04/01/17 11:02:53  04/03/17 06:32:41       NaN                NaN  04/03/17 12:22:23            NaN  04/26/17 14:27:08  05/18/17 12:29:49      NaN           NaN            NaN     05/18/17 12:33:24               NaN  05/19/17 11:33:01  05/19/17 11:34:24                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:46:05   NaN   NaN   NaN  SKLEPY     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
1      6767  6767   NaN  11. zdane na magazyn       1/sklepy         2         23  03/21/17 00:00:00   70  03/31/17 00:00:00  04/07/17 00:00:00   111 - 36  4483-69-1153   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:26       NaN  03/24/17 16:19:39  03/28/17 12:33:25    NaN  04/01/17 10:56:05  04/03/17 06:32:48       NaN                NaN  04/06/17 08:59:47            NaN  04/06/17 09:00:09  04/06/17 09:03:18      NaN           NaN            NaN     04/13/17 07:27:04               NaN  04/26/17 07:21:32  04/26/17 09:48:54                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:46:12   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
2      6771  6771   NaN  11. zdane na magazyn       1/sklepy         2         27  03/21/17 00:00:00   77  03/31/17 00:00:00  04/11/17 00:00:00   111 - 54  4483-69-1208   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:58       NaN  03/24/17 16:19:39  03/28/17 12:27:52    NaN  04/01/17 11:03:42  04/03/17 06:31:46       NaN                NaN  04/03/17 12:22:07            NaN  04/06/17 06:05:45  04/06/17 06:07:49      NaN           NaN            NaN     04/11/17 08:55:50               NaN  04/13/17 11:01:11  04/19/17 07:42:07                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:44:20   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
3      6772  6772   NaN  11. zdane na magazyn       1/sklepy         2         28  03/21/17 00:00:00   76  03/31/17 00:00:00  04/11/17 00:00:00  111 - B2C  4483-69-1208   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:58       NaN  03/24/17 16:19:39  03/28/17 12:28:30    NaN  03/30/17 16:04:29  03/31/17 06:23:39       NaN                NaN  03/31/17 09:52:54            NaN  04/06/17 06:05:38  04/06/17 06:07:58      NaN           NaN            NaN     04/11/17 08:43:23               NaN  04/19/17 07:00:11  04/19/17 11:02:19                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  03/31/17 08:19:45   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
4      6777  6777   NaN  11. zdane na magazyn       1/sklepy         2         33  03/21/17 00:00:00   77  03/31/17 00:00:00  04/11/17 00:00:00   111 - 12  4483-69-1208   0    0   0    0   1    0   2    0   2    0   2    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                6  03/21/17 08:54:58       NaN  03/24/17 16:19:39  03/28/17 12:27:52    NaN  04/01/17 11:03:42  04/03/17 06:31:46       NaN                NaN  04/03/17 12:22:07            NaN  04/06/17 06:05:45  04/06/17 06:07:49      NaN           NaN            NaN     04/11/17 08:55:50               NaN  04/13/17 11:01:11  04/19/17 07:42:07                       NaN                               NaN        NaN       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN          -        NaN                   NaN  Pud.jedn. 19D/białe              NaN            NaN            NaN  04/03/17 07:44:20   NaN   NaN   NaN  SKLEPY     1   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN

In [2]:
df.columns

Index(['Autonumer', 'ID', 'pilny', 'etap', 'nr zam klienta', 'nr ew zam',
       'nr poz zam', 'data zam', 'plan', 'termin zam', 'termin prod',
       'kontrahent', 'model', 'z34', 'z345', 'z35', 'z355', 'z36', 'z365',
       'z37', 'z375', 'z38', 'z385', 'z39', 'z395', 'z40', 'z405', 'z41',
       'z415', 'z42', 'z425', 'z43', 'z435', 'z44', 'z445', 'z45', 'z46',
       'z47', 'z48', 'z49', 'z50', 'szwalnia szyjąca', 'przyjete', 'zam surow',
       'oczekujące', 'rozkrój', 'ploter', 'ścienianie', 'przygotowawcza',
       'mag kroji', 'kroje niekompletne', 'na szwalnii', 'chol bez ozdób',
       'MAG 2', 'MAG 3', 'Overlock', 'szycie ręczne', 'przedmontażowy',
       'przygotowane komplety', 'wklejone zakładki', 'montaż',
       'zdane na magazyn', 'zlecone do wyprodukowania',
       'zrealizowana produkcja zewnętrzna', 'wstrzymane', 'odrzucone',
       'wyd oblek obcasy', 'wyd oblek podsuwki', 'wyd oblek podpodeszwy',
       'kto obleka obcas', 'kto obleka podsuwka', 'kto obleka podpodeszwa',
       'zrealizowno oblek obcas', 'zrealizowno oblek podsuwka',
       'zrealizowno oblek podpodeszwa', 'uwagi prod', 'uwagi inne',
       'uwagi całe zamówienie', 'pudełko', 'nr 2 zam klienta',
       'drukowano plan', 'wydruk etykiet', 'pole1', 'pole2', 'pole3', 'pole4',
       'pole5', 'pole6', 'pole7', 'pole8', 'pole9', 'pole10', 'pole11',
       'pole12', 'pole13', 'pole14', 'pole15'],
      dtype='str')

In [3]:
df.shape

(30885, 97)

In [4]:
display(df['nr zam klienta'])

0        1/sklepy
1        1/sklepy
2        1/sklepy
3        1/sklepy
4        1/sklepy
           ...
30880         151
30881         191
30882         170
30883         155
30884         191
Name: nr zam klienta, Length: 30885, dtype: str

In [5]:
import pandas as pd, re

df_data = pd.read_csv("../data/dane.csv", dtype=str, keep_default_na=False, na_values=[""])

DATE_RE = re.compile(r"^\s*\d{1,2}[/-]\d{1,2}[/-]\d{2,4}([ T]\d{1,2}:\d{2}(:\d{2})?)?\s*$")

date_cols, empty_cols, mixed = [], [], {}
for c in df_data.columns:
    s = df_data[c].dropna()
    if s.empty:
        empty_cols.append(c)          # brak danych -> nie da się orzec
        continue
    hit = s.str.match(DATE_RE).mean()
    if hit == 1.0:
        date_cols.append(c)
    elif hit > 0:
        mixed[c] = hit                # do ręcznego obejrzenia/

In [6]:
display(date_cols)

['data zam',
 'termin zam',
 'termin prod',
 'przyjete',
 'oczekujące',
 'rozkrój',
 'ploter',
 'ścienianie',
 'przygotowawcza',
 'na szwalnii',
 'MAG 2',
 'MAG 3',
 'Overlock',
 'przedmontażowy',
 'przygotowane komplety',
 'montaż',
 'zdane na magazyn',
 'zlecone do wyprodukowania',
 'zrealizowana produkcja zewnętrzna',
 'wstrzymane',
 'odrzucone',
 'drukowano plan',
 'wydruk etykiet',
 'pole1',
 'pole2',
 'pole3']

In [7]:
display(empty_cols)

['zam surow',
 'mag kroji',
 'kroje niekompletne',
 'chol bez ozdób',
 'szycie ręczne',
 'wklejone zakładki',
 'wyd oblek obcasy',
 'wyd oblek podsuwki',
 'wyd oblek podpodeszwy',
 'kto obleka obcas',
 'kto obleka podsuwka',
 'kto obleka podpodeszwa',
 'zrealizowno oblek obcas',
 'zrealizowno oblek podsuwka',
 'zrealizowno oblek podpodeszwa',
 'pole7',
 'pole8',
 'pole9',
 'pole10',
 'pole11',
 'pole12',
 'pole13',
 'pole14',
 'pole15']

In [8]:
print(len(empty_cols))

24

In [9]:
df['Autonumer'].duplicated().any()

np.False_

In [10]:
df['Autonumer'].nunique()

30885

In [11]:
df.duplicated().any()

np.False_

In [12]:
display(df['ID'].duplicated().any())
display(df['ID'].duplicated().sum())

np.True_

np.int64(234)

In [13]:
df[df['ID'].duplicated(keep=False)].sort_values('ID').head(4)

      Autonumer     ID pilny                  etap nr zam klienta nr ew zam nr poz zam           data zam  plan         termin zam        termin prod kontrahent          model z34 z345 z35 z355 z36 z365 z37 z375 z38 z385 z39 z395 z40 z405 z41 z415 z42 z425 z43 z435 z44 z445 z45 z46 z47 z48 z49 z50 szwalnia szyjąca           przyjete zam surow         oczekujące            rozkrój             ploter         ścienianie     przygotowawcza mag kroji kroje niekompletne        na szwalnii chol bez ozdób              MAG 2              MAG 3 Overlock szycie ręczne przedmontażowy przygotowane komplety wklejone zakładki             montaż   zdane na magazyn zlecone do wyprodukowania zrealizowana produkcja zewnętrzna         wstrzymane odrzucone wyd oblek obcasy wyd oblek podsuwki wyd oblek podpodeszwy kto obleka obcas kto obleka podsuwka kto obleka podpodeszwa zrealizowno oblek obcas zrealizowno oblek podsuwka zrealizowno oblek podpodeszwa uwagi prod        uwagi inne uwagi całe zamówienie pudełko nr 2 zam klienta drukowano plan wydruk etykiet              pole1 pole2 pole3 pole4             pole5 pole6 pole7 pole8 pole9 pole10 pole11 pole12 pole13 pole14 pole15
5911      18361  18361   NaN  11. zdane na magazyn            201         0          0  05/31/17 00:00:00  2692  08/07/17 00:00:00  10/19/17 00:00:00   111 - 47  9351-69-981-M   0    0   0    0   1    0   2    0   2    0   2    0   0    0   1    0   0    0   0    0   0    0   0   0   0   0   0   0                8  06/02/17 14:06:36       NaN  09/22/17 12:02:44  09/28/17 10:13:25                NaN  10/11/17 15:02:17  10/12/17 07:16:11       NaN                NaN  10/30/17 15:09:27            NaN  11/27/17 13:10:37  11/27/17 13:12:11      NaN           NaN            NaN     11/28/17 05:58:32               NaN  12/06/17 15:16:08  12/13/17 13:03:36                       NaN                               NaN  06/02/17 00:00:00       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN  SUWALKI-PLAZA-47                   NaN     NaN              NaN            NaN            NaN  10/12/17 14:43:51   NaN   NaN   NaN            SKLEPY     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
18525     40963  18361   NaN             2 gatunek            201         0          0  05/31/17 00:00:00  2692  08/07/17 00:00:00  10/19/17 00:00:00   111 - 47  9351-69-981-M   0    0   0    0   0    0   0    0   0    0   0    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0                8  06/02/17 14:06:36       NaN  09/22/17 12:02:44  09/28/17 10:13:25                NaN  10/11/17 15:02:17  10/12/17 07:16:11       NaN                NaN  10/30/17 15:09:27            NaN  11/27/17 13:10:37  11/27/17 13:12:11      NaN           NaN            NaN     11/28/17 05:58:32               NaN  12/06/17 15:16:08                NaN                       NaN                               NaN  06/02/17 00:00:00       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN  SUWALKI-PLAZA-47                   NaN     NaN              NaN            NaN            NaN  10/12/17 14:43:51   NaN   NaN   NaN            SKLEPY     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
18671     41109  29968   NaN             2 gatunek          20062         0          0  09/22/17 00:00:00  3288  11/21/17 00:00:00  02/07/18 00:00:00  200-72000    1494-69-433   0    0   0    0   0    0   0    0   0    0   0    0   1    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0               12  09/26/17 13:07:40       NaN  10/28/17 07:55:27                NaN  11/15/17 09:51:39  11/23/17 06:54:35  11/24/17 08:09:35       NaN                NaN  11/29/17 06:33:51            NaN  12/05/17 13:30:27  12/05/17 13:31:30      NaN           NaN            NaN     12/06/17 08:17:10               NaN  12/07/17 14:03:26                NaN                       NaN                               NaN  10/18/17 14:34:59       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN   wysyłka: Grójec                   NaN     NaN        20062//BA            NaN            NaN  11/24/17 14:55:05   NaN   NaN   NaN  SKLEPY+SORBOS+DH     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN
8077      29968  29968   NaN  11. zdane na magazyn          20062         0          0  09/22/17 00:00:00  3288  11/21/17 00:00:00  02/07/18 00:00:00  200-72000    1494-69-433   0    0   0    0   1    0   1    0   2    0   2    0   0    0   0    0   0    0   0    0   0    0   0   0   0   0   0   0               12  09/26/17 13:07:40       NaN  10/28/17 07:55:27                NaN  11/15/17 09:51:39  11/23/17 06:54:35  11/24/17 08:09:35       NaN                NaN  11/29/17 06:33:51            NaN  12/05/17 13:30:27  12/05/17 13:31:30      NaN           NaN            NaN     12/06/17 08:17:10               NaN  12/07/17 14:03:26  12/15/17 12:57:33                       NaN                               NaN  10/18/17 14:34:59       NaN              NaN                NaN                   NaN              NaN                 NaN                    NaN                     NaN                        NaN                           NaN        NaN   wysyłka: Grójec                   NaN     NaN        20062//BA            NaN            NaN  11/24/17 14:55:05   NaN   NaN   NaN  SKLEPY+SORBOS+DH     2   NaN   NaN   NaN    NaN    NaN    NaN    NaN    NaN    NaN

In [14]:
df[df['ID'].duplicated(keep=False)].groupby('ID').nunique(dropna=True).gt(1).sum().sort_values(ascending=False).loc[lambda s: s > 0]

Autonumer    233
etap         233
z36          212
z40          210
z38          189
z39          178
z37          163
z375          13
z395          13
z385          13
z365          12
z35            7
z41            5
dtype: int64

In [15]:
size_cols = [
    "z34", "z345", "z35", "z355", "z36", "z365",
    "z37", "z375", "z38", "z385", "z39", "z395",
    "z40", "z405", "z41", "z415", "z42", "z425",
    "z43", "z435", "z44", "z445", "z45", "z46",
    "z47", "z48", "z49", "z50"
]

kolumny_do_pominiecia = set(size_cols + ["etap"] + ['ID'])

duplikaty_id = df[df.duplicated("ID", keep=False)].copy()

def rozniace_sie_kolumny(grupa):
    roznice = []

    for kolumna in df.columns:
        if kolumna in kolumny_do_pominiecia:
            continue

        wartosci = grupa[kolumna].astype("string").fillna("").unique()

        if len(wartosci) > 1:
            roznice.append(kolumna)

    return roznice

raport_roznic = (
    duplikaty_id
    .groupby("ID", group_keys=False)
    .apply(rozniace_sie_kolumny)
    .rename("roznice_poza_etapem_i_rozmiarowka")
)

raport_roznic.head()

ID
18361    [Autonumer, zdane na magazyn]
29968    [Autonumer, zdane na magazyn]
30547    [Autonumer, zdane na magazyn]
30553    [Autonumer, zdane na magazyn]
30559    [Autonumer, zdane na magazyn]
Name: roznice_poza_etapem_i_rozmiarowka, dtype: object

In [16]:
raport_roznic.value_counts()

roznice_poza_etapem_i_rozmiarowka
[Autonumer, zdane na magazyn]    233
Name: count, dtype: int64

In [ ]:
df['etap'].nunique()

26

In [19]:
df['etap'].value_counts()

etap
11. zdane na magazyn      21695
odrzucone                  3355
wstrzymane                 1384
8. przyg komplety          1130
2. oczekujące               673
7. MAG 3                    520
Szwalnia 6                  420
0c                          230
2 gatunek                   222
1b. zam krótki termin       221
4b. przygotowawcza          194
4. ścienianie               174
1a. zam długi termin        152
3. rozkrój                  106
3p. ploter                  102
6. MAG 2                     64
5k. komplety szwalnia        56
10. montaż                   51
Szwalnia 1                   38
B2. wydane 2 komplety        31
Szwalnia 5                   25
Szwalnia 10                  20
uszkodzone anulowane         12
7o. Overlock                  6
7p. Mag przedmontażowy        2
10b. montaż 2                 2
Name: count, dtype: int64

In [20]:
df['kontrahent'].nunique()

279

In [21]:
df['kontrahent'].value_counts()

kontrahent
200-100        3309
200-2165       1612
200-0012       1250
EVA MINGE      1003
114 - B2C       901
               ...
LA MANIA          1
OTICO             1
088               1
200-2             1
200-40928/2       1
Name: count, Length: 279, dtype: int64

In [22]:
df['model'].nunique()

1816

In [23]:
df['model'].value_counts()

model
7769-69-124-F      167
8137-69-077-F      145
9301-69-1062-M     129
7744-69-113-M      127
7787-69-010        117
                  ...
9373-69-1596-WF      1
6339-69-1630         1
6371-69-1017-L       1
6431-69-1056-L       1
1528-69-015          1
Name: count, Length: 1816, dtype: int64

In [ ]:
df['szwalnia szyjąca'].nunique()

11

In [25]:
df['szwalnia szyjąca'].value_counts()

szwalnia szyjąca
6     14087
0      9169
1      3114
10     1174
5      1085
12      997
8       915
7       272
11       51
13       14
9         7
Name: count, dtype: int64